### ISSUE TITLE
Feature request: Ability to silently dequeue TA tickets

### ISSUE THREAD

**Issue by dengeist** [vampaynani/TATickets#7]
Sometimes, mentors need to take a ticket out of the queue without alerting a student. Tickets might be left over from a previous day, or a student might ask for help and then promptly solve their own issue. An endpoint like `/ticket-next-silent` would be great. Or maybe `/ticket-dequeue` to minimize confusion and make autocompletion easier.

**Comment by bookcasey** [comment]
https://github.com/vampaynani/TATickets/pull/8

The syntax is `/ticket-next silent` 🤫

**Comment by dengeist** [comment]
Oh! Thanks, Casey 😅
